"""init schema

Revision ID: 4332763385ee
Revises: 
Create Date: 2026-07-31 16:23:17.294670

"""
from alembic import op
import sqlalchemy as sa


revision = '4332763385ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('custom_picture', sa.Boolean(), nullable=False),
    sa.Column('notification_settings', sa.JSON(), nullable=False),
    sa.Column('notifications_read_at', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('friendships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('friend_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('simplify_by_default', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_shape', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=8000), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('repeat_interval', sa.String(length=20), nullable=False),
    sa.Column('next_repeat', sa.String(length=30), nullable=True),
    sa.Column('email_reminder', sa.Boolean(), nullable=False),
    sa.Column('email_reminder_in_advance', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Boolean(), nullable=False),
    sa.Column('transaction_confirmed', sa.Boolean(), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expense_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('comment_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_expense_id'), 'comments', ['expense_id'], unique=False)
    op.create_table('expense_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expense_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('paid_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('owed_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_shares_expense_id'), 'expense_shares', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_shares_user_id'), 'expense_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_shares_user_id'), table_name='expense_shares')
    op.drop_index(op.f('ix_expense_shares_expense_id'), table_name='expense_shares')
    op.drop_table('expense_shares')
    op.drop_index(op.f('ix_comments_expense_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('group_members')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('groups')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('currencies')
    op.drop_table('categories')
    # ### end Alembic commands ###
