"""add phone_number and timezone to users

Revision ID: a334ac22035c
Revises: aaaec85bde9f
Create Date: 2026-07-31 17:12:12.325255

"""
from alembic import op
import sqlalchemy as sa


revision = 'a334ac22035c'
down_revision = 'aaaec85bde9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    op.alter_column('users', 'timezone', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
