"""widen expense date columns

Revision ID: aaaec85bde9f
Revises: 4332763385ee
Create Date: 2026-07-31 16:25:59.919336

"""
from alembic import op
import sqlalchemy as sa


revision = 'aaaec85bde9f'
down_revision = '4332763385ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'date',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('expenses', 'next_repeat',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'next_repeat',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('expenses', 'date',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
